platform :ios, '10.0'

target 'MeuMetro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.7.3'
#  pod 'AlamofireObjectMapper', '~> 5.2.0'
#  pod 'ObjectMapper', '~> 3.4.2'
  pod 'RxSwift', '~> 4.5.0'
  pod 'CodableAlamofire', '~> 1.1.0'

  # Pods for MeuMetro

  target 'MeuMetroTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MeuMetroUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
